USE SCHEMA DEMO;
ALTER TABLE HELLO_WORLD ADD COLUMN AGE NUMBER;
ALTER TABLE HELLO_WORLD ADD COLUMN GENDER VARCHAR;
ALTER TABLE HELLO_WORLD ADD COLUMN EMAIL VARCHAR;

CREATE TABLE IF NOT EXISTS BYE_WORLD
(
   NEW_NAME VARCHAR
  ,LAST_NAME VARCHAR
);